server:
  context-path: /july
  tomcat:
    uri-encoding: utf-8

spring:
  profiles:
    active: dev
  freemarker:
      cache: false
      charset: UTF-8
      check-template-location: true
      content-type: text/html
      expose-request-attributes: true
      expose-session-attributes: true
      request-context-attribute: request
      suffix: .ftl


mybatis:
  type-aliases-package: com.fanxl.july.entity
  mapper-locations: classpath:mapper/*.xml

mapper:
    mappers:
        - com.fanxl.july.util.MyMapper
    not-empty: false
    identity: MYSQL

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql